service: image-url-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    BUCKET_NAME: product-assets
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::product-assets/products/*

functions:
  uploadImage:
    handler: handler.uploadImage
    events:
      - http:
          path: /upload
          method: post
          cors: true

